name: 'android-recovery-action' 
author: 'XenonTheInertG' 
description: 'Standalone Android Recovery Builder using github action.'

runs:
  using: docker
  image: Dockerfile

branding:
  icon: 'box'
  color: 'yellow'
